module.exports = [
  {
    id: 1,
    job_id: 3,
    user_id: 1,
    // name: "John Doe",
    // email: "john.doe@gmail.com",
    // password: "328-456-7820",
    // resumeUrl: "https://www.quora.com/How-can-I-create-a-link-for-my-resume",
    // linkedInUrl: "https://www.linkedin.com/company/mary-poppins",
  },
  {
    id: 2,
    job_id: 1,
    user_id: 3,
    // name: "David Champ",
    // email: "david.champ@gmail.com",
    // password: "222-458-7890",
    // resumeUrl: "https://www.quora.com/How-can-I-create-a-link-for-my-resume",
    // linkedInUrl: "https://www.linkedin.com/company/mary-poppins",
  },
  {
    id: 3,
    job_id: 2,
    user_id: 2,
    // name: "Alex Green",
    // email: "alex.green@gmail.com",
    // password: "823-456-9890",
    // resumeUrl: "https://www.quora.com/How-can-I-create-a-link-for-my-resume",
    // linkedInUrl: "https://www.linkedin.com/company/mary-poppins",
  },
];
