module.exports = [
  {
    id: 1,
    company: "St Pauls Hospital",
    website:
      "https://www.providencehealthcare.org/hospitals-residences/st-paul%27s-hospital",
    email: "joba@email.com",
    phone: "323-444-7890",
    address: "789 Wood St, Vancouver, BC",
    startDate: "22-04-2022",
    endDate: "26-04-2022",
    position: "Caregiver",
    pay: "$45",
    description: "one awesome product for photographers",
    user_id: 2,
  },
  {
    id: 2,
    company: "St Pauls Hospital",
    website:
      "https://www.providencehealthcare.org/hospitals-residences/st-paul%27s-hospital",
    email: "paulsclinic@email.com",
    phone: "323-444-7890",
    address: "789 Wood St, Vancouver, BC",
    startDate: "22-04-2022",
    endDate: "26-04-2022",
    position: "Doctor",
    pay: "$45",
    description: "one awesome product for chefs",
    user_id: 3,
  },
  {
    id: 3,
    company: "St Pauls Hospital",
    website:
      "https://www.providencehealthcare.org/hospitals-residences/st-paul%27s-hospital",
    email: "crosshospital@email.com",
    phone: "323-444-7890",
    address: "789 Wood St, Vancouver, BC",
    startDate: "22-04-2022",
    endDate: "26-04-2022",
    position: "Doctor",
    pay: "$95",
    description: "one awesome product for musicians",
    user_id: 1,
  },
];
